version: '3.9'
services:
  gpt-api-clone:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    volumes:
      - .:/home/app
    links:
      - ollama-two

  ollama-two:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-two:/root/.ollama

volumes:
  ollama-two: