POST http://localhost:3003/v1/engines/llama2/completions
Content-Type: application/json
#Authorization ignored for now
Authorization: Bearer YOUR_API_KEY

{
  "prompt": "hi, how are you?",
  "max_tokens": 15,
  "temperature": 0.8
}
